### ISSUE TITLE
`Could not resolve the dependencies` when running `bundle exec librarian-chef install`

### ISSUE THREAD

**Issue by codeword** [pivotal-sprout/sprout-vim#4]
The Cheffile references a forked copy of the homebrew cookbook under http://github.com/pivotal/homebrew-chef using branch 'unset-rubyopt-environment-variable'.  That copies version is still 1.6.5 but homebrew has moved to 1.9.0

I think other dependent cookbooks depend on homebrew > 1.6.5 so librarian-chef is unable to resolve the dependencies.

We should either stop using the fork of homebrew (I don't understand what the fork is doing) or update/rebase the fork to its upstream/masters HEAD

**Comment by wendorf** [comment]
Looks like this issue was made irrelevant as of [this commit](https://github.com/pivotal-sprout/sprout-vim/commit/c80e7b92ec30af28340703631b9f8c88c79f963d).
