### ISSUE TITLE
Build error during vim plugin installation

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-vim#7]
Created https://github.com/pivotal/vim-config/issues/5 as this seems to be a problem with https://github.com/pivotal/vim-config installtion

See: https://travis-ci.org/pivotal-sprout/sprout-vim/builds/136839029

**Comment by aramprice** [comment]
One solution might be to use https://github.com/luan/vimfiles as the default config repo, see [sprout-vim/attributes/default.rb:4](https://github.com/pivotal-sprout/sprout-vim/blob/master/attributes/default.rb#L4) since many pivotal teams are using this config successfully.

**Comment by nertzy** [comment]
pivotal/vim-config#5 is now fixed.

**Comment by aramprice** [comment]
@nertzy thanks! seems like there are further problems but none related to the actual installation of the vim-config plugins.

From: https://travis-ci.org/pivotal-sprout/sprout-vim/
```
  1) sprout-vim installs MacVim, adds the .vim directory, and installs tmux
     Failure/Error: expect(system('soloist')).to be_true
       expected true to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/integration/cookbook_spec.rb:15:in `block (2 levels) in <top (required)>'
```
